### ISSUE TITLE
python3兼容问题

### ISSUE THREAD

**Issue by Oneplus** [bfdw/gcf#1]
```
Traceback (most recent call last):
  File "/Users/yijialiu/anaconda3/envs/py36/bin/gcf", line 7, in <module>
    from gcf.gcf import main
  File "/Users/yijialiu/anaconda3/envs/py36/lib/python3.6/site-packages/gcf/gcf.py", line 7, in <module>
    import gcf_mining as gm
ModuleNotFoundError: No module named 'gcf_mining'
```

貌似不符合python3 import语法。

**Comment by bfdw** [comment]
是的，确实不符合，下个小版本就把它改掉。对python3的兼容还要一点点时间 : )

**Comment by bfdw** [comment]
I just tried to fix it and it should support python3 now. I already pushed the new version to PyPI, but PyPI may need several hours to catch it. Thanks for your comment! Enjoy! 😝
